---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - make
  become: yes

- name: Clone create_ap
  become: yes
  git: repo=https://github.com/oblique/create_ap dest=/usr/local/src/create_ap depth=1

- name: Install create_ap
  make: chdir=/usr/local/src/create_ap target=install
  become: yes